### ISSUE TITLE
Add Hostgroup/Usergroup to sudo rule

### ISSUE THREAD

**Issue by torbatux** [Nosmoht/ansible-module-ipa#9]
It would be cool to have the Hostgroup/Usergroup parameter also added to the sudo rules, in order to add Hostgroup/Usergroup to a sudo rule

**Comment by Nosmoht** [comment]
Hi @torbatux,

this is fixed with https://github.com/Nosmoht/ansible-module-ipa/pull/10.

Please let me know if you find any bugs.
